repos:
  # Basic sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
        args: ["--maxkb=5000"]

  # Black
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        language_version: python3.13

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.13

  # MyPy
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: false